name: Build Air Cull Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Run build (force remapJar + jar)
        run: ./gradlew clean build remapJar jar --no-daemon --info

      - name: List build outputs
        run: ls -R build/libs || true

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: AirCull-Mod
          path: build/libs/*.jar
