name: Build Fabric Mod (Java 21)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build jar --no-daemon

      - name: Upload built jar
        uses: actions/upload-artifact@v4
        with:
          name: air-cull-jar
          path: build/libs/*.jar
